/**
 * Auto-categorization service for expenses based on payee name patterns.
 */

export interface CategoryConfig {
    name: string;
    color: string;
    patterns: RegExp;
}

export const CATEGORIES: CategoryConfig[] = [
    {
        name: 'Dining',
        color: '#f472b6', // pink
        patterns: /UBER\s*EATS|SKIP\s*THE\s*DISHES|DOORDASH|RITUAL|ARTIGIANO|OJAS|TCM\s*@|TST-|STARBUCKS|TIM\s*HORTON|MCDONALD|A&W|SUBWAY|SUSHI|PIZZA|RESTAURANT|CAFE|COFFEE|BREW|GRUBHUB|FOODORA|INSTACART|JUST\s*EAT|CHICK-FIL|WENDY|POPEYES|KFC|TACO\s*BELL|CHIPOTLE|PANERA|PANDA\s*EXPRESS|DAIRY\s*QUEEN|DUNKIN|SECOND\s*CUP|BLENZ|WAVES|BOBA|BUBBLE\s*TEA|NANDO|EARLS|CACTUS\s*CLUB|JOEY|WHITE\s*SPOT|BOSTON\s*PIZZA|MILESTONE|MOXIE|ORIGINAL\s*JOE|BROWNIES|SWISS\s*CHALET|HARVEYS|MARY\s*BROWN|POKE|RAMEN|THAI|INDIAN|VIETNAMESE|GREEK|ITALIAN|MEXICAN|BURRITO|BURGER|GRILL|BISTRO|EATERY|TAVERN|PUB|BAR\s*&|LOUNGE|DINER|SNACK|PATISSERIE|CROISSANT|BREKA|CATCH\s*122|PIE\s*HOLE|WOLF\s*IN\s*THE\s*FOG|PALMS\s*BEACH|YASMA|WANIDA|WASHINGTON\s*AVE|BREAK\s*CAFE|WILD\s*FLOUR/i,
    },
    {
        name: 'Groceries',
        color: '#34d399', // green
        patterns: /SHOPPERS|SAVE\s*ON|GROCERY|SUPERMARKET|FARM\s*BOY|LOBLAWS|METRO|SOBEYS|COSTCO|WAL-?MART|NO\s*FRILLS|T&T|WHOLE\s*FOODS|FIELDSTONE|RED\s*ROOSTER|SUPERSTORE|REAL\s*CANADIAN|INDEPENDENT\s*GROCER|FRESHCO|FOOD\s*BASICS|GIANT\s*TIGER|DOLLARAMA|DOLLAR\s*TREE|IGA|SAFEWAY|CO-OP|THRIFTY|QUALITY\s*FOODS|LONGOS|PUSATERI|EATALY|BULK\s*BARN|NATURAL\s*FOODS|ORGANIC|PRODUCE|BUTCHER|MEAT\s*SHOP|FISH\s*MARKET|TRADER\s*JOE|NESPRESSO|FAIRWAY\s*MARKET|WALGREENS|LONDON\s*DRUGS|SS\s*SURREY|7-?ELEVEN|CIRCLE\s*K|CHAN'S\s*KING/i,
    },
    {
        name: 'Utilities',
        color: '#60a5fa', // blue
        patterns: /TELUS|ROGERS|BELL|FIDO|HYDRO|ENBRIDGE|FORTIS|SHAW|VIDEOTRON|KOODO|VIRGIN\s*MOBILE|FREEDOM\s*MOBILE|PUBLIC\s*MOBILE|CHATR|LUCKY\s*MOBILE|BC\s*HYDRO|HYDRO\s*ONE|TORONTO\s*HYDRO|ALECTRA|HORIZON|ENERGY|ELECTRIC|GAS\s*COMPANY|WATER\s*UTIL|ATCO|EPCOR|SASKPOWER|MANITOBA\s*HYDRO|NOVA\s*SCOTIA\s*POWER/i,
    },
    {
        name: 'Entertainment',
        color: '#a78bfa', // purple
        patterns: /HARRY\s*POTTER|CINEPLEX|SPOTIFY|NETFLIX|DISNEY|AMAZON\s*PRIME|APPLE\s*TV|CRAVE|PARAMOUNT|HBO|YOUTUBE|TWITCH|STEAM|PLAYSTATION|XBOX|NINTENDO|THEATRE|CINEMA|MOVIE|CONCERT|TICKET|TICKETMASTER|STUBHUB|EVENTBRITE|LIVE\s*NATION|BOWLING|ARCADE|MINI\s*GOLF|ESCAPE\s*ROOM|LASER\s*TAG|MUSEUM|GALLERY|ZOO|AQUARIUM|AMUSEMENT|THEME\s*PARK|WONDERLAND|RIPLEY|IMAX|VR\s*ARCADE|COMEDY|IMPROV|FESTIVAL|FAIR|SURREY\s*PARKS|WESTSHOREPARKS|SPIRIT\s*OF\s*CHRISTMAS/i,
    },
    {
        name: 'Shopping',
        color: '#fbbf24', // amber
        patterns: /GQ\s*HERMAN|ZARA|H&M|WINNERS|MARSHALLS|HOMESENSE|SIMONS|NORDSTROM|HUDSON|INDIGO|AMAZON|BEST\s*BUY|APPLE\s*STORE|UNIQLO|GAP|OLD\s*NAVY|IKEA|LULULEMON|ARITZIA|ROOTS|SPORTCHEK|ATMOSPHERE|DECATHLON|CANADIAN\s*TIRE|HOME\s*DEPOT|LOWES|RONA|HOME\s*HARDWARE|STAPLES|OFFICE\s*DEPOT|MICHAELS|JOANN|HOBBY|CRAFT|SEPHORA|ULTA|BATH\s*&\s*BODY|LUSH|SHOPIFY|ETSY|EBAY|ALIEXPRESS|SHEIN|FASHION|CLOTHING|APPAREL|WEAR|FOOTWEAR|SHOE|NIKE|ADIDAS|PUMA|REEBOK|NEW\s*BALANCE|SKECHERS|FOOT\s*LOCKER|CHAMPS|FINISH\s*LINE|JEWELRY|WATCH|ACCESSORY|BAG|PURSE|WALLET|SUNGLASSES|EYEWEAR|FURNITURE|MATTRESS|BED\s*BATH|WAYFAIR|STRUCTUBE|EQ3|CRATE\s*&\s*BARREL|POTTERY\s*BARN|WEST\s*ELM|CB2|WILLIAMS\s*SONOMA|TEMU|CANADIAN\s*PACIFIC\s*STOR/i,
    },
    {
        name: 'Transport',
        color: '#fb923c', // orange
        patterns: /UBER(?!\s*EATS)|LYFT|PRESTO|TRANSIT|PARKING|PETRO|ESSO|SHELL|CANADIAN\s*TIRE\s*GAS|CAR2GO|EVO\s*CAR|ZIPCAR|MODO|COMMUNAUTO|TURO|ENTERPRISE|HERTZ|BUDGET|AVIS|NATIONAL|ALAMO|U-HAUL|PENSKE|HOME\s*DEPOT\s*RENT|CAR\s*WASH|JIFFY\s*LUBE|OIL\s*CHANGE|MIDAS|MR\s*LUBE|CANADIAN\s*TIRE\s*AUTO|KAL\s*TIRE|FOUNTAIN\s*TIRE|GAS\s*STATION|HUSKY|CHEVRON|MOBIL|PIONEER|7-ELEVEN\s*GAS|CIRCLE\s*K\s*GAS|IMPARK|EASYPARK|HONK|PAYBYPHONE|GREEN\s*P|TTC|TRANSLINK|OC\s*TRANSPO|STM|METROLINX|GO\s*TRANSIT|VIA\s*RAIL|GREYHOUND|MEGABUS|FLIXBUS|AIRLINE|FLIGHT|AIR\s*CANADA|WESTJET|PORTER|FLAIR|SWOOP|DELTA|UNITED|AMERICAN\s*AIR|ALASKA\s*AIR|BCF|BC\s*FERR|EV\s*CHARGING|R\s*PARKING/i,
    },
    {
        name: 'Health',
        color: '#f87171', // red
        patterns: /PHARMACY|DRUG\s*MART|REXALL|DENTIST|DOCTOR|CLINIC|HOSPITAL|PHYSIO|CHIRO|OPTOM|MEDICAL|HEALTH|GYM|FITNESS|YOGA|PILATES|CROSSFIT|ORANGE\s*THEORY|F45|GOODLIFE|YMCA|EQUINOX|PLANET\s*FITNESS|ANYTIME\s*FITNESS|FIT4LESS|LA\s*FITNESS|MASSAGE|SPA|WELLNESS|THERAPY|COUNSELL|PSYCH|DERMAT|VISION|OPTICAL|LENSCRAFTERS|BAILEY|HAKIM|SPECSAVERS|LIFE\s*LABS|DYNACARE|CML|BLOOD|LAB|VITAMIN|SUPPLEMENT|GNC|POPEYE|CANNABIS|SQDC|OCS|BCCS|AGLC|OLIVE\s*FERTILITY|WA\s*DEPT.*HEALTH|DEPT\s*OF\s*HEALTH/i,
    },
    {
        name: 'Subscriptions',
        color: '#06b6d4', // cyan
        patterns: /REDDIT|PATREON|SUBSTACK|MEDIUM|NOTION|FIGMA|CANVA|ADOBE|MICROSOFT|GOOGLE\s*ONE|DROPBOX|ICLOUD|APPLE\s*ONE|GITHUB|LINKEDIN|TWITTER|X\.COM|OPENAI|CHATGPT|ANTHROPIC|CLAUDE|AWS|AZURE|DIGITAL\s*OCEAN|VERCEL|NETLIFY|HEROKU|SQUARESPACE|WIX|WORDPRESS|MAILCHIMP|HUBSPOT|SALESFORCE|ZOOM|SLACK|NOTION|ASANA|TRELLO|MONDAY|CLICKUP|TODOIST|EVERNOTE|1PASSWORD|LASTPASS|BITWARDEN|NORDVPN|EXPRESSVPN|SURFSHARK|NEWS|GLOBE|POST|TIMES|JOURNAL|ECONOMIST|ATHLETIC|DAZN|TSN|SPORTSNET|NBA|NFL|MLB|FLOATPLANE|NEBULA|CURIOSITY|SKILLSHARE|MASTERCLASS|COURSERA|UDEMY|BRILLIANT|DUOLINGO|BABBEL|HEADSPACE|CALM|PELOTON|STRAVA|ALLTRAILS|MYFITNESSPAL|NOOM|REPLIT|CURSOR\s*AI|APPLE\.COM|TONKON\s*TORP/i,
    },
    {
        name: 'Travel',
        color: '#8b5cf6', // violet
        patterns: /HOTEL|MOTEL|INN|RESORT|AIRBNB|VRBO|BOOKING\.COM|EXPEDIA|HOTELS\.COM|MARRIOTT|HILTON|HYATT|SHERATON|WESTIN|FOUR\s*SEASONS|FAIRMONT|RADISSON|HOLIDAY\s*INN|BEST\s*WESTERN|TRAVELODGE|SUPER\s*8|DAYS\s*INN|COMFORT\s*INN|BANFF\s*SPRINGS|PACIFIC\s*SANDS|BEACH\s*RESO/i,
    },
    {
        name: 'Services',
        color: '#ec4899', // fuchsia
        patterns: /DRYCLEAN|DRY\s*CLEAN|LAUNDRY|ALTERATION|TAILOR|REPAIR|LOCKSMITH|MOVING|STORAGE|CLEANING|MAID|HOUSEKEEP|PLUMBER|ELECTRICIAN|HVAC|HANDYMAN|CONTRACTOR|LAWYER|LEGAL|NOTARY|ACCOUNTANT|TAX\s*PREP|From\s*chequing/i,
    },
    {
        name: 'Financial',
        color: '#10b981', // emerald
        patterns: /WEALTHSIMPLE|QUESTRADE|TD\s*DIRECT|RBC\s*DIRECT|SCOTIA\s*ITRADE|BMO\s*INVESTORLINE|CIBC\s*INVESTOR|NATIONAL\s*BANK|DESJARDINS|TANGERINE|SIMPLII|EQ\s*BANK|MANULIFE|SUN\s*LIFE|GREAT\s*WEST|CANADA\s*LIFE|INDUSTRIAL\s*ALLIANCE|LONDON\s*LIFE|RBC\s*INSURANCE|TD\s*INSURANCE|AVIVA|INTACT|DESJARDINS\s*INSURANCE|SONNET|BELAIR|ECONOMICAL|COOPERATORS|WAWANESA|PAYPAL|WISE|TRANSFERWISE|REMITLY|WESTERN\s*UNION|MONEYGRAM|INTERAC|CREDIT\s*UNION|CAISSE|ATM|BANK\s*FEE|SERVICE\s*CHARGE|INTEREST|FINANCE\s*CHARGE|NSF|OVERDRAFT/i,
    },
];

export const CATEGORY_COLORS: Record<string, string> = {
    Dining: '#f472b6',
    Groceries: '#34d399',
    Utilities: '#60a5fa',
    Entertainment: '#a78bfa',
    Shopping: '#fbbf24',
    Transport: '#fb923c',
    Health: '#f87171',
    Subscriptions: '#06b6d4',
    Travel: '#8b5cf6',
    Services: '#ec4899',
    Financial: '#10b981',
    Other: '#94a3b8',
};

/**
 * Auto-categorize an expense based on payee name.
 */
export function categorizeExpense(payee: string): string {
    for (const category of CATEGORIES) {
        if (category.patterns.test(payee)) {
            return category.name;
        }
    }
    return 'Other';
}
